#!/usr/bin/env bun
/**
 * PMM AGENTS.md Generator
 * ========================
 * Generates an AGENTS.md from PMM DB state for a project.
 * Keeps AI agent instructions current without manual maintenance.
 *
 * Usage: bun scripts/pmm-generate-agents.ts <project> [--write]
 */
import { openDb, queryAll, queryOne } from "../src/db";
import { writeFileSync, existsSync } from "node:fs";
import { join } from "node:path";

const args = process.argv.slice(2);
if (!args.length) { console.log("Usage: bun scripts/pmm-generate-agents.ts <project> [--write]"); process.exit(1); }
const projectName = args[0]!;
const writeMode = args.includes("--write");

const db = openDb();

try {
  const project = queryOne(db, "SELECT * FROM projects WHERE name = ?", [projectName]) as any;
  if (!project) { console.log(`Project "${projectName}" not found`); process.exit(1); }

  const milestones = queryAll(db, "SELECT name, due, status, acceptance_criteria FROM milestones WHERE project_id = ? ORDER BY id", [project.id]) as any[];
  const features = queryAll(db, "SELECT name, status, priority FROM features WHERE project_id = ? ORDER BY priority LIMIT 10", [project.id]) as any[];
  const decisions = queryAll(db, "SELECT question, decision, rationale FROM decisions WHERE project_id = ? ORDER BY id DESC LIMIT 8", [project.id]) as any[];
  const roadblocks = queryAll(db, "SELECT description, severity, resolution FROM roadblocks WHERE project_id = ? AND resolved_at IS NULL", [project.id]) as any[];
  const deps = queryAll(db,
    "SELECT p.name, d.description FROM dependencies d JOIN projects p ON d.to_project_id = p.id WHERE d.from_project_id = ?", [project.id]) as any[];

  const done = milestones.filter((m: any) => m.status === "completed").length;
  const total = milestones.length;
  const activeFeatures = features.filter((f: any) => f.status !== "done");

  let md = `# AGENTS.md — ${project.name}\n\n`;
  md += `> Auto-generated by PMM on ${new Date().toISOString().slice(0, 10)}. \n`;
  md += `> Source: PMM DB. Do not edit manually — regenerate with \`bun scripts/pmm-generate-agents.ts "${project.name}" --write\`\n\n`;

  md += `## Current State\n`;
  md += `- **Phase:** ${project.phase} | **Priority:** ${project.priority} | **Health:** ${project.health}\n`;
  md += `- **Milestones:** ${done}/${total} complete\n`;
  md += `- **Active Features:** ${activeFeatures.length}\n`;
  md += `- **Roadblocks:** ${roadblocks.length}\n\n`;

  if (deps.length) {
    md += `## Dependencies\n`;
    for (const d of deps) md += `- **${d.name}**: ${d.description || "depends on"}\n`;
    md += "\n";
  }

  if (milestones.length) {
    md += `## Milestones\n`;
    for (const m of milestones) {
      const icon = m.status === "completed" ? "✓" : m.status === "in-progress" ? "▶" : m.status === "blocked" ? "✗" : "○";
      md += `- ${icon} **${m.name}**${m.due ? ` (due: ${m.due})` : ""}\n`;
      if (m.acceptance_criteria) md += `  - Criteria: ${m.acceptance_criteria.slice(0, 120)}\n`;
    }
    md += "\n";
  }

  if (activeFeatures.length) {
    md += `## Active Features\n`;
    for (const f of activeFeatures) {
      md += `- ${f.name} [${f.priority}]\n`;
    }
    md += "\n";
  }

  if (roadblocks.length) {
    md += `## Roadblocks\n`;
    for (const r of roadblocks) {
      md += `- [${r.severity}] ${r.description}\n`;
    }
    md += "\n";
  }

  if (decisions.length) {
    md += `## Key Decisions\n`;
    for (const d of decisions) {
      md += `- **Q:** ${d.question.slice(0, 100)}\n  **A:** ${d.decision.slice(0, 100)}\n`;
    }
    md += "\n";
  }

  md += `## Commands\n`;
  md += `- Health: \`bun scripts/pmm.ts health\`\n`;
  md += `- Context: \`bun scripts/pmm-context-inject.ts --project "${project.name}"\`\n`;
  md += `- Regenerate this file: \`bun scripts/pmm-generate-agents.ts "${project.name}" --write\`\n`;

  if (writeMode) {
    const path = join(import.meta.dir, "..", "AGENTS.md");
    writeFileSync(path, md);
    console.log(`Written to ${path}`);
  } else {
    console.log(md);
  }
} finally {
  db.close();
}
