import type {
  AgentHandle,
  AgentSpawner,
  CommandResult,
  CommandRunner,
  ExecCommandParams,
  ExecutionRuntime,
  InvokeSkillParams,
  LifecycleManager,
  SkillInvoker,
  SkillResult,
  SpawnAgentParams,
  WorkerResult,
} from "../contract";
import { buildWorkerPrompt, injectWorkerTracking } from "./claude-code";

// ══ OpenCode CLI Adapter ═══════════════════════════════════════════
// Agent spawn:   agent(...)
// Skill invoke:  skill(...)
// Command run:   terminal(...)
// File read:     read(...)
// File write:    write(...)
// Hook mechanism: opencode.json hooks
// Hook events:   sessionStart, sessionEnd, preToolUse, postToolUse
// Instruction:   TEST.md

/**
 * OpenCode CLI Adapter — Maps the PMM Execution Contract to OpenCode CLI primitives.
 *
 * Generated by: bun scripts/pmm.ts exec inject --harness opencode
 * Harness: OpenCode CLI (planned)
 * Generated: 2026-05-04
 *
 * Adapter maps PMM Execution Contract to OpenCode CLI native primitives.
 *
 * Contract Method          → OpenCode CLI Primitive
 * ─────────────────────────────────────────────────
 * agents.spawn()          → agent()
 * skills.invoke()         → skill()
 * commands.exec()         → terminal()
 * lifecycle.onSession*()  → opencode.json hooks
 */

/**
 * OpenCodeAdapter — maps the PMM Execution Contract to OpenCode CLI primitives.
 *
 * Contract Method          → OpenCode CLI Primitive
 * ─────────────────────────────────────────────────
 * agents.spawn()          → agent()
 * skills.invoke()         → skill()
 * commands.exec()         → terminal()
 * lifecycle.onSession*()  → opencode.json hooks
 */

export class OpenCodeAdapter implements ExecutionRuntime {
  readonly harness = "opencode";

  agents: AgentSpawner = {
    spawn: async (params: SpawnAgentParams): Promise<AgentHandle> => {
      // OpenCode CLI: agent({ agent_type: params.agentType, model: params.model, ... })
      // Execution is LLM-mediated — this method documents the expected call shape.
      return {
        workerId: params.workerId ?? -1,
        status: "pending",
        cancel: async () => {
          /* Cancel not supported in OpenCode CLI */
        },
        getResult: async (): Promise<WorkerResult> => ({
          status: "completed",
          summary: "Agent execution is LLM-mediated via agent().",
        }),
      };
    },
  };

  skills: SkillInvoker = {
    invoke: async (params: InvokeSkillParams): Promise<SkillResult> => {
      // OpenCode CLI: skill({ skill: params.skillName })
      return {
        skillName: params.skillName,
        output: "Skill invocation is LLM-mediated via skill().",
      };
    },
  };

  commands: CommandRunner = {
    exec: async (_params: ExecCommandParams): Promise<CommandResult> => {
      return { stdout: "", stderr: "", exitCode: 0 };
    },
  };

  lifecycle: LifecycleManager = {
    onSessionStart: (_handler) => {
      /* opencode.json hooks → sessionStart */
    },
    onSessionEnd: (_handler) => {
      /* opencode.json hooks → sessionEnd */
    },
    onPreToolUse: (_handler) => {
      /* opencode.json hooks → preToolUse */
    },
    onPostToolUse: (_handler) => {
      /* opencode.json hooks → postToolUse */
    },
    onUserPromptSubmit: (_handler) => {
      /* Not mapped — no corresponding hook event */
    },
  };
}

/** Singleton instance. Replace with harness-native instantiation if needed. */
export const runtime: ExecutionRuntime = new OpenCodeAdapter();
